name: LifePvP
version: '${project.version}'
main: azuazu3939.lifepvp.LifePvP
api-version: 1.15

commands:
  pvp:
    permission: LifePvP.Command.pvp
    description: "pvpできるやつ。"

permissions:
  LifePvP.Command.pvp:
    default: false