name: LifePvP
version: '${project.version}'
main: azuazu3939.lifepvp.LifePvP
api-version: 1.15

commands:
  pvp:
    permission: LifePvP.Command.pvp
    description: "pvpできるやつ。"
  pvpItemList:
    permission: LifePvP.Command.pvpItemList
    description: "確認用。"
    aliases: [PIL, pil]

permissions:
  LifePvP.Command.pvp:
    default: false
  LifePvP.Command.pvpItemList:
    default: true